from numpy import dtype

def DI(df):
   col = ['시술 시기 코드', '배란 자극 여부', '남성 주 불임 원인', '남성 부 불임 원인', '여성 주 불임 원인',
       '여성 부 불임 원인', '부부 주 불임 원인', '부부 부 불임 원인', '불명확 불임 원인', '불임 원인 - 난관 질환',
       '불임 원인 - 남성 요인', '불임 원인 - 배란 장애',  '불임 원인 - 정자 농도',
       '불임 원인 - 정자 형태', '시술 당시 나이', '임신 시도 또는 마지막 임신 경과 연수', '총 시술 횟수',
       '클리닉 내 총 시술 횟수', 'IVF 시술 횟수', 'DI 시술 횟수', '총 임신 횟수', 'IVF 임신 횟수',
       'DI 임신 횟수', '총 출산 횟수', 'IVF 출산 횟수', 'DI 출산 횟수', '정자 기증자 나이', '특시유_IUI', '특시유_ICI', '특시유_GIFT', '특시유_IVI']

   df_DI = df[df['시술 유형'] == -100][col].copy()

   d_types = {'시술 시기 코드': dtype('int64'),
      '배란 자극 여부': dtype('int64'),
      '남성 주 불임 원인': dtype('int64'),
      '남성 부 불임 원인': dtype('int64'),
      '여성 주 불임 원인': dtype('int64'),
      '여성 부 불임 원인': dtype('int64'),
      '부부 주 불임 원인': dtype('int64'),
      '부부 부 불임 원인': dtype('int64'),
      '불명확 불임 원인': dtype('int64'),
      '불임 원인 - 난관 질환': dtype('int64'),
      '불임 원인 - 남성 요인': dtype('int64'),
      '불임 원인 - 배란 장애': dtype('int64'),
      '불임 원인 - 정자 농도': dtype('int64'),
      '불임 원인 - 정자 형태': dtype('int64'),
      '시술 당시 나이': dtype('int64'),
      '임신 시도 또는 마지막 임신 경과 연수': dtype('int64'),
      '총 시술 횟수': dtype('int64'),
      '클리닉 내 총 시술 횟수': dtype('int64'),
      'IVF 시술 횟수': dtype('int64'),
      'DI 시술 횟수': dtype('int64'),
      '총 임신 횟수': dtype('int64'),
      'IVF 임신 횟수': dtype('int64'),
      'DI 임신 횟수': dtype('int64'),
      '총 출산 횟수': dtype('int64'),
      'IVF 출산 횟수': dtype('int64'),
      'DI 출산 횟수': dtype('int64'),
      '정자 기증자 나이': dtype('int64'),
      '특시유_IUI': dtype('int64'),
      '특시유_ICI': dtype('int64'),
      '특시유_GIFT': dtype('int64'),
      '특시유_IVI': dtype('int64')}

   for c in df_DI.columns:
      df_DI[c] = df_DI[c].astype(d_types[c], errors='ignore')

   categorical_columns_list_DI = [
      '시술 시기 코드', '남성 주 불임 원인', '남성 부 불임 원인', '여성 주 불임 원인', '여성 부 불임 원인', '부부 주 불임 원인',
      '부부 부 불임 원인', '불명확 불임 원인', '불임 원인 - 난관 질환', '불임 원인 - 남성 요인', '불임 원인 - 배란 장애',
      '불임 원인 - 정자 농도', '불임 원인 - 정자 형태', '특시유_IUI', '특시유_ICI', '특시유_GIFT', '특시유_IVI',
   ]
    
   return df_DI, categorical_columns_list_DI


def IVF(df):
     col = ['시술 시기 코드', '배란 자극 여부', '단일 배아 이식 여부', '착상 전 유전 검사 사용 여부', '착상 전 유전 진단 사용 여부', '남성 주 불임 원인', '남성 부 불임 원인', '여성 주 불임 원인', '여성 부 불임 원인', '부부 주 불임 원인', '부부 부 불임 원인', '불명확 불임 원인',
        '불임 원인 - 난관 질환', '불임 원인 - 남성 요인', '불임 원인 - 배란 장애', '불임 원인 - 자궁경부 문제', '불임 원인 - 자궁내막증', '불임 원인 - 정자 농도', '불임 원인 - 정자 면역학적 요인', '불임 원인 - 정자 운동성', '불임 원인 - 정자 형태',
        '동결 배아 사용 여부', '신선 배아 사용 여부', '기증 배아 사용 여부', '대리모 여부', 'PGD 시술 여부', 'PGS 시술 여부', '난자 출처', '정자 출처', '시술 당시 나이', '임신 시도 또는 마지막 임신 경과 연수', '총 시술 횟수', '클리닉 내 총 시술 횟수',
        'IVF 시술 횟수', 'DI 시술 횟수', '총 임신 횟수', 'IVF 임신 횟수', 'DI 임신 횟수', '총 출산 횟수', 'IVF 출산 횟수', 'DI 출산 횟수', '총 생성 배아 수', '미세주입된 난자 수', '미세주입에서 생성된 배아 수', '이식된 배아 수',
        '미세주입 배아 이식 수', '저장된 배아 수', '미세주입 후 저장된 배아 수', '해동된 배아 수', '해동 난자 수', '수집된 신선 난자 수', '저장된 신선 난자 수', '혼합된 난자 수', '파트너 정자와 혼합된 난자 수', '기증자 정자와 혼합된 난자 수', '난자 기증자 나이', '정자 기증자 나이',
        '난자 해동 경과일', '난자 혼합 경과일', '배아 이식 경과일', '배아 해동 경과일', 'PGS', 'PGD', '특시유_ICSI', '특시유_BLASTOCYST', '특시유_AH', '특시유_Unknown', '특시유_IVF', '특시유_ICSI_ICSI',
        '특시유_IVF_IVF', '특시유_ICSI_Unknown', '특시유_BLASTOCYST_IVF', '특시유_IVF_Unknown', '특시유_ICSI/BLASTOCYST', '특시유_IVF/BLASTOCYST', '특시유_ICSI/AH', '특시유_IVF/AH', '특시유_ICSI/BLASTOCYST_IVF/BLASTOCYST', '배생이_기증용', '배생이_난자 저장용', '배생이_배아 저장용',
        '임신 경험 여부', '출산 경험 여부', '시술 경험 여부', '단일_배아_이식_여부_수정', '클리닉 외 시술 여부', '배아 출처', '특정 시술 유형 (합산 유형)', '유전검사 (합산통합)', '불임원인 (합산통합)', '남성 불임 요인', '여성 불임 요인', 'IVF_ICSI_최상조건',
        'IVF에서 생성된 배아 수', 'IVF 배아 이식 수', 'IVF 후 저장된 배아 수', '폐기된 배아 수', '미세주입 배아 실패 수', 'IVF 배아 실패 수', '해당 주기 난자 주인 나이', '나이_X_이식수', '배란자극_X_이식배아수', '잉여_배아_수', '이식률', '수정률',
        '총 경과일 합계', '총 임신 실패 횟수', 'IVF 임신 실패 횟수', 'DI 임신 실패 횟수', '총 유산 횟수', 'IVF 유산 횟수', 'DI 유산 횟수', '기증자 나이 합산', '미세 주입 성공률', '난자 채취 이후 경과일']
     df_IVF = df[df['시술 유형'] == 100][df['배생이_현재 시술용'] == 1][df['이식된 배아 수'] != 0][col].copy()

     d_type = {'시술 시기 코드': dtype('int64'),
     '배란 자극 여부': dtype('int64'),
     '단일 배아 이식 여부': dtype('int64'),
     '착상 전 유전 검사 사용 여부': dtype('int64'),
     '착상 전 유전 진단 사용 여부': dtype('int64'),
     '남성 주 불임 원인': dtype('int64'),
     '남성 부 불임 원인': dtype('int64'),
     '여성 주 불임 원인': dtype('int64'),
     '여성 부 불임 원인': dtype('int64'),
     '부부 주 불임 원인': dtype('int64'),
     '부부 부 불임 원인': dtype('int64'),
     '불명확 불임 원인': dtype('int64'),
     '불임 원인 - 난관 질환': dtype('int64'),
     '불임 원인 - 남성 요인': dtype('int64'),
     '불임 원인 - 배란 장애': dtype('int64'),
     '불임 원인 - 자궁경부 문제': dtype('int64'),
     '불임 원인 - 자궁내막증': dtype('int64'),
     '불임 원인 - 정자 농도': dtype('int64'),
     '불임 원인 - 정자 면역학적 요인': dtype('int64'),
     '불임 원인 - 정자 운동성': dtype('int64'),
     '불임 원인 - 정자 형태': dtype('int64'),
     '동결 배아 사용 여부': dtype('int64'),
     '신선 배아 사용 여부': dtype('int64'),
     '기증 배아 사용 여부': dtype('int64'),
     '대리모 여부': dtype('int64'),
     'PGD 시술 여부': dtype('int64'),
     'PGS 시술 여부': dtype('int64'),
     '난자 출처': dtype('int64'),
     '정자 출처': dtype('int64'),
     '시술 당시 나이': dtype('int64'),
     '임신 시도 또는 마지막 임신 경과 연수': dtype('int64'),
     '총 시술 횟수': dtype('int64'),
     '클리닉 내 총 시술 횟수': dtype('int64'),
     'IVF 시술 횟수': dtype('int64'),
     'DI 시술 횟수': dtype('int64'),
     '총 임신 횟수': dtype('int64'),
     'IVF 임신 횟수': dtype('int64'),
     'DI 임신 횟수': dtype('int64'),
     '총 출산 횟수': dtype('int64'),
     'IVF 출산 횟수': dtype('int64'),
     'DI 출산 횟수': dtype('int64'),
     '총 생성 배아 수': dtype('int64'),
     '미세주입된 난자 수': dtype('int64'),
     '미세주입에서 생성된 배아 수': dtype('int64'),
     '이식된 배아 수': dtype('int64'),
     '미세주입 배아 이식 수': dtype('int64'),
     '저장된 배아 수': dtype('int64'),
     '미세주입 후 저장된 배아 수': dtype('int64'),
     '해동된 배아 수': dtype('int64'),
     '해동 난자 수': dtype('int64'),
     '수집된 신선 난자 수': dtype('int64'),
     '저장된 신선 난자 수': dtype('int64'),
     '혼합된 난자 수': dtype('int64'),
     '파트너 정자와 혼합된 난자 수': dtype('int64'),
     '기증자 정자와 혼합된 난자 수': dtype('int64'),
     '난자 기증자 나이': dtype('int64'),
     '정자 기증자 나이': dtype('int64'),
     '난자 해동 경과일': dtype('int64'),
     '난자 혼합 경과일': dtype('int64'),
     '배아 이식 경과일': dtype('int64'),
     '배아 해동 경과일': dtype('int64'),
     'PGS': dtype('int64'),
     'PGD': dtype('int64'),
     '특시유_ICSI': dtype('int64'),
     '특시유_BLASTOCYST': dtype('int64'),
     '특시유_AH': dtype('int64'),
     '특시유_Unknown': dtype('int64'),
     '특시유_IVF': dtype('int64'),
     '특시유_ICSI_ICSI': dtype('int64'),
     '특시유_IVF_IVF': dtype('int64'),
     '특시유_ICSI_Unknown': dtype('int64'),
     '특시유_BLASTOCYST_IVF': dtype('int64'),
     '특시유_IVF_Unknown': dtype('int64'),
     '특시유_ICSI/BLASTOCYST': dtype('int64'),
     '특시유_IVF/BLASTOCYST': dtype('int64'),
     '특시유_ICSI/AH': dtype('int64'),
     '특시유_IVF/AH': dtype('int64'),
     '특시유_ICSI/BLASTOCYST_IVF/BLASTOCYST': dtype('int64'),
     '배생이_기증용': dtype('int64'),
     '배생이_난자 저장용': dtype('int64'),
     '배생이_배아 저장용': dtype('int64'),
     '임신 경험 여부': dtype('int64'),
     '출산 경험 여부': dtype('int64'),
     '시술 경험 여부': dtype('int64'),
     '단일_배아_이식_여부_수정': dtype('int64'),
     '클리닉 외 시술 여부': dtype('bool'),
     '배아 출처': dtype('int64'),
     '특정 시술 유형 (합산 유형)': dtype('int64'),
     '유전검사 (합산통합)': dtype('int64'),
     '불임원인 (합산통합)': dtype('int64'),
     '남성 불임 요인': dtype('int64'),
     '여성 불임 요인': dtype('int64'),
     'IVF_ICSI_최상조건': dtype('int64'),
     'IVF에서 생성된 배아 수': dtype('int64'),
     'IVF 배아 이식 수': dtype('int64'),
     'IVF 후 저장된 배아 수': dtype('int64'),
     '폐기된 배아 수': dtype('int64'),
     '미세주입 배아 실패 수': dtype('int64'),
     'IVF 배아 실패 수': dtype('int64'),
     '해당 주기 난자 주인 나이': dtype('int64'),
     '나이_X_이식수': dtype('int64'),
     '배란자극_X_이식배아수': dtype('int64'),
     '잉여_배아_수': dtype('int64'),
     '이식률': dtype('float64'),
     '수정률': dtype('float64'),
     '총 경과일 합계': dtype('int64'),
     '총 임신 실패 횟수': dtype('int64'),
     'IVF 임신 실패 횟수': dtype('int64'),
     'DI 임신 실패 횟수': dtype('int64'),
     '총 유산 횟수': dtype('int64'),
     'IVF 유산 횟수': dtype('int64'),
     'DI 유산 횟수': dtype('int64'),
     '기증자 나이 합산': dtype('int64'),
     '미세 주입 성공률': dtype('float64'),
     '난자 채취 이후 경과일': dtype('int64')}
     for c in df_IVF.columns:
        df_IVF[c] = df_IVF[c].astype(d_type[c], errors='ignore')

     categorical_columns_list_IVF_NOW_YES = [
        'PGS', 'PGD', '특시유_ICSI', '특시유_BLASTOCYST', '특시유_AH', '특시유_Unknown', '특시유_IVF', '특시유_ICSI_ICSI', '특시유_IVF_IVF', '특시유_ICSI_Unknown', '특시유_BLASTOCYST_IVF',
        '특시유_IVF_Unknown', '배생이_기증용', '배생이_난자 저장용', '배생이_배아 저장용', '임신 경험 여부', '출산 경험 여부', '시술 경험 여부', '클리닉 외 시술 여부', '배아 출처', '특정 시술 유형 (합산 유형)', '불임원인 (합산통합)',
        '남성 불임 요인', '여성 불임 요인', 'IVF_ICSI_최상조건', '시술 시기 코드', '배란 자극 여부', '단일 배아 이식 여부', '남성 주 불임 원인', '남성 부 불임 원인', '여성 주 불임 원인', '여성 부 불임 원인', '부부 주 불임 원인',
        '부부 부 불임 원인', '불명확 불임 원인', '불임 원인 - 난관 질환', '불임 원인 - 남성 요인', '불임 원인 - 배란 장애', '불임 원인 - 자궁경부 문제', '불임 원인 - 자궁내막증', '불임 원인 - 정자 농도', '불임 원인 - 정자 면역학적 요인', 
        '불임 원인 - 정자 운동성', '불임 원인 - 정자 형태', '동결 배아 사용 여부', '신선 배아 사용 여부', '기증 배아 사용 여부', '대리모 여부', 'PGD 시술 여부', 'PGS 시술 여부', '난자 출처', '정자 출처'
     ]
    
     return df_IVF, categorical_columns_list_IVF_NOW_YES
 
 
 
def BLASTOCYST(df):
   col = ['시술 시기 코드', '배란 자극 여부', '단일 배아 이식 여부', '착상 전 유전 검사 사용 여부',
       '착상 전 유전 진단 사용 여부', '남성 주 불임 원인', '남성 부 불임 원인', '여성 주 불임 원인',
       '여성 부 불임 원인', '부부 주 불임 원인', '부부 부 불임 원인', '불명확 불임 원인', '불임 원인 - 난관 질환',
       '불임 원인 - 남성 요인', '불임 원인 - 배란 장애', '불임 원인 - 자궁내막증', '불임 원인 - 정자 농도',
       '동결 배아 사용 여부', '신선 배아 사용 여부', '기증 배아 사용 여부', '대리모 여부', 'PGD 시술 여부',
       'PGS 시술 여부', '난자 출처', '정자 출처', '시술 당시 나이', '임신 시도 또는 마지막 임신 경과 연수',
       '총 시술 횟수', '클리닉 내 총 시술 횟수', 'IVF 시술 횟수', 'DI 시술 횟수', '총 임신 횟수',
       'IVF 임신 횟수', 'DI 임신 횟수', '총 출산 횟수', 'IVF 출산 횟수', 'DI 출산 횟수',
       '총 생성 배아 수', '미세주입된 난자 수', '미세주입에서 생성된 배아 수', '이식된 배아 수',
       '미세주입 배아 이식 수', '저장된 배아 수', '미세주입 후 저장된 배아 수', '해동된 배아 수', '해동 난자 수',
       '수집된 신선 난자 수', '저장된 신선 난자 수', '혼합된 난자 수', '파트너 정자와 혼합된 난자 수',
       '기증자 정자와 혼합된 난자 수', '난자 기증자 나이', '정자 기증자 나이', '난자 혼합 경과일', '배아 이식 경과일',
       '배아 해동 경과일', 'PGS', 'PGD', '특시유_ICSI', '특시유_IVF', '특시유_BLASTOCYST_IVF',
       '특시유_ICSI/BLASTOCYST', '특시유_IVF/BLASTOCYST',
       '특시유_ICSI/BLASTOCYST_IVF/BLASTOCYST', '배생이_기증용', '임신 경험 여부', '출산 경험 여부',
       '시술 경험 여부', '단일_배아_이식_여부_수정', '클리닉 외 시술 여부', '배아 출처',
       '특정 시술 유형 (합산 유형)', '유전검사 (합산통합)', '불임원인 (합산통합)', '남성 불임 요인',
       '여성 불임 요인', 'IVF_ICSI_최상조건', 'IVF에서 생성된 배아 수', 'IVF 배아 이식 수',
       'IVF 후 저장된 배아 수', '폐기된 배아 수', '미세주입 배아 실패 수', 'IVF 배아 실패 수',
       '해당 주기 난자 주인 나이', '나이_X_이식수', '배란자극_X_이식배아수', '잉여_배아_수', '이식률', '수정률',
       '총 경과일 합계', '총 임신 실패 횟수', 'IVF 임신 실패 횟수', 'DI 임신 실패 횟수', '총 유산 횟수',
       'IVF 유산 횟수', 'DI 유산 횟수', '기증자 나이 합산', '미세 주입 성공률', '난자 채취 이후 경과일']
   df_BLASTOCYST = df[df['특시유_BLASTOCYST'] == 1][df['이식된 배아 수'] != 0][df['시술 유형'] == 100][df['배생이_현재 시술용'] == 1][col].copy()
   d_types = {'시술 시기 코드': dtype('int64'),
     '배란 자극 여부': dtype('int64'),
     '단일 배아 이식 여부': dtype('int64'),
     '착상 전 유전 검사 사용 여부': dtype('int64'),
     '착상 전 유전 진단 사용 여부': dtype('int64'),
     '남성 주 불임 원인': dtype('int64'),
     '남성 부 불임 원인': dtype('int64'),
     '여성 주 불임 원인': dtype('int64'),
     '여성 부 불임 원인': dtype('int64'),
     '부부 주 불임 원인': dtype('int64'),
     '부부 부 불임 원인': dtype('int64'),
     '불명확 불임 원인': dtype('int64'),
     '불임 원인 - 난관 질환': dtype('int64'),
     '불임 원인 - 남성 요인': dtype('int64'),
     '불임 원인 - 배란 장애': dtype('int64'),
     '불임 원인 - 자궁내막증': dtype('int64'),
     '불임 원인 - 정자 농도': dtype('int64'),
     '동결 배아 사용 여부': dtype('int64'),
     '신선 배아 사용 여부': dtype('int64'),
     '기증 배아 사용 여부': dtype('int64'),
     '대리모 여부': dtype('int64'),
     'PGD 시술 여부': dtype('int64'),
     'PGS 시술 여부': dtype('int64'),
     '난자 출처': dtype('int64'),
     '정자 출처': dtype('int64'),
     '시술 당시 나이': dtype('int64'),
     '임신 시도 또는 마지막 임신 경과 연수': dtype('int64'),
     '총 시술 횟수': dtype('int64'),
     '클리닉 내 총 시술 횟수': dtype('int64'),
     'IVF 시술 횟수': dtype('int64'),
     'DI 시술 횟수': dtype('int64'),
     '총 임신 횟수': dtype('int64'),
     'IVF 임신 횟수': dtype('int64'),
     'DI 임신 횟수': dtype('int64'),
     '총 출산 횟수': dtype('int64'),
     'IVF 출산 횟수': dtype('int64'),
     'DI 출산 횟수': dtype('int64'),
     '총 생성 배아 수': dtype('int64'),
     '미세주입된 난자 수': dtype('int64'),
     '미세주입에서 생성된 배아 수': dtype('int64'),
     '이식된 배아 수': dtype('int64'),
     '미세주입 배아 이식 수': dtype('int64'),
     '저장된 배아 수': dtype('int64'),
     '미세주입 후 저장된 배아 수': dtype('int64'),
     '해동된 배아 수': dtype('int64'),
     '해동 난자 수': dtype('int64'),
     '수집된 신선 난자 수': dtype('int64'),
     '저장된 신선 난자 수': dtype('int64'),
     '혼합된 난자 수': dtype('int64'),
     '파트너 정자와 혼합된 난자 수': dtype('int64'),
     '기증자 정자와 혼합된 난자 수': dtype('int64'),
     '난자 기증자 나이': dtype('int64'),
     '정자 기증자 나이': dtype('int64'),
     '난자 혼합 경과일': dtype('int64'),
     '배아 이식 경과일': dtype('int64'),
     '배아 해동 경과일': dtype('int64'),
     'PGS': dtype('int64'),
     'PGD': dtype('int64'),
     '특시유_ICSI': dtype('int64'),
     '특시유_IVF': dtype('int64'),
     '특시유_BLASTOCYST_IVF': dtype('int64'),
     '특시유_ICSI/BLASTOCYST': dtype('int64'),
     '특시유_IVF/BLASTOCYST': dtype('int64'),
     '특시유_ICSI/BLASTOCYST_IVF/BLASTOCYST': dtype('int64'),
     '배생이_기증용': dtype('int64'),
     '임신 경험 여부': dtype('int64'),
     '출산 경험 여부': dtype('int64'),
     '시술 경험 여부': dtype('int64'),
     '단일_배아_이식_여부_수정': dtype('int64'),
     '클리닉 외 시술 여부': dtype('bool'),
     '배아 출처': dtype('int64'),
     '특정 시술 유형 (합산 유형)': dtype('int64'),
     '유전검사 (합산통합)': dtype('int64'),
     '불임원인 (합산통합)': dtype('int64'),
     '남성 불임 요인': dtype('int64'),
     '여성 불임 요인': dtype('int64'),
     'IVF_ICSI_최상조건': dtype('int64'),
     'IVF에서 생성된 배아 수': dtype('int64'),
     'IVF 배아 이식 수': dtype('int64'),
     'IVF 후 저장된 배아 수': dtype('int64'),
     '폐기된 배아 수': dtype('int64'),
     '미세주입 배아 실패 수': dtype('int64'),
     'IVF 배아 실패 수': dtype('int64'),
     '해당 주기 난자 주인 나이': dtype('int64'),
     '나이_X_이식수': dtype('int64'),
     '배란자극_X_이식배아수': dtype('int64'),
     '잉여_배아_수': dtype('int64'),
     '이식률': dtype('float64'),
     '수정률': dtype('float64'),
     '총 경과일 합계': dtype('int64'),
     '총 임신 실패 횟수': dtype('int64'),
     'IVF 임신 실패 횟수': dtype('int64'),
     'DI 임신 실패 횟수': dtype('int64'),
     '총 유산 횟수': dtype('int64'),
     'IVF 유산 횟수': dtype('int64'),
     'DI 유산 횟수': dtype('int64'),
     '기증자 나이 합산': dtype('int64'),
     '미세 주입 성공률': dtype('float64'),
     '난자 채취 이후 경과일': dtype('int64')}
   for c in df_BLASTOCYST.columns:
      df_BLASTOCYST[c] = df_BLASTOCYST[c].astype(d_types[c], errors='ignore')

   return df_BLASTOCYST

def AH(df):
   col = ['시술 시기 코드', '배란 자극 여부', '단일 배아 이식 여부', '착상 전 유전 검사 사용 여부',
       '착상 전 유전 진단 사용 여부', '남성 주 불임 원인', '남성 부 불임 원인', '여성 주 불임 원인',
       '여성 부 불임 원인', '부부 주 불임 원인', '부부 부 불임 원인', '불명확 불임 원인', '불임 원인 - 난관 질환',
       '불임 원인 - 남성 요인', '불임 원인 - 배란 장애', '불임 원인 - 자궁내막증', '동결 배아 사용 여부',
       '신선 배아 사용 여부', '기증 배아 사용 여부', '대리모 여부', 'PGD 시술 여부', 'PGS 시술 여부',
       '난자 출처', '정자 출처', '시술 당시 나이', '임신 시도 또는 마지막 임신 경과 연수', '총 시술 횟수',
       '클리닉 내 총 시술 횟수', 'IVF 시술 횟수', 'DI 시술 횟수', '총 임신 횟수', 'IVF 임신 횟수',
       'DI 임신 횟수', '총 출산 횟수', 'IVF 출산 횟수', 'DI 출산 횟수', '총 생성 배아 수',
       '미세주입된 난자 수', '미세주입에서 생성된 배아 수', '이식된 배아 수', '미세주입 배아 이식 수', '저장된 배아 수',
       '미세주입 후 저장된 배아 수', '해동된 배아 수', '해동 난자 수', '수집된 신선 난자 수', '저장된 신선 난자 수',
       '혼합된 난자 수', '파트너 정자와 혼합된 난자 수', '기증자 정자와 혼합된 난자 수', '난자 기증자 나이',
       '정자 기증자 나이', '난자 혼합 경과일', '배아 이식 경과일', '배아 해동 경과일', 'PGS', 'PGD',
       '특시유_ICSI', '특시유_Unknown', '특시유_IVF', '특시유_ICSI/AH', '특시유_IVF/AH',
       '배생이_기증용', '임신 경험 여부', '출산 경험 여부', '시술 경험 여부', '단일_배아_이식_여부_수정',
       '클리닉 외 시술 여부', '배아 출처', '특정 시술 유형 (합산 유형)', '유전검사 (합산통합)',
       '불임원인 (합산통합)', '남성 불임 요인', '여성 불임 요인', 'IVF_ICSI_최상조건',
       'IVF에서 생성된 배아 수', 'IVF 배아 이식 수', 'IVF 후 저장된 배아 수', '폐기된 배아 수',
       '미세주입 배아 실패 수', 'IVF 배아 실패 수', '해당 주기 난자 주인 나이', '나이_X_이식수',
       '배란자극_X_이식배아수', '잉여_배아_수', '이식률', '수정률', '총 경과일 합계', '총 임신 실패 횟수',
       'IVF 임신 실패 횟수', 'DI 임신 실패 횟수', '총 유산 횟수', 'IVF 유산 횟수', 'DI 유산 횟수',
       '기증자 나이 합산', '미세 주입 성공률', '난자 채취 이후 경과일']

   df_AH = df[df['특시유_AH'] == 1][df['이식된 배아 수'] != 0][df['시술 유형'] == 100][df['배생이_현재 시술용'] == 1][col].copy()
   d_types = {'시술 시기 코드': dtype('int64'),
     '배란 자극 여부': dtype('int64'),
     '단일 배아 이식 여부': dtype('int64'),
     '착상 전 유전 검사 사용 여부': dtype('int64'),
     '착상 전 유전 진단 사용 여부': dtype('int64'),
     '남성 주 불임 원인': dtype('int64'),
     '남성 부 불임 원인': dtype('int64'),
     '여성 주 불임 원인': dtype('int64'),
     '여성 부 불임 원인': dtype('int64'),
     '부부 주 불임 원인': dtype('int64'),
     '부부 부 불임 원인': dtype('int64'),
     '불명확 불임 원인': dtype('int64'),
     '불임 원인 - 난관 질환': dtype('int64'),
     '불임 원인 - 남성 요인': dtype('int64'),
     '불임 원인 - 배란 장애': dtype('int64'),
     '불임 원인 - 자궁내막증': dtype('int64'),
     '동결 배아 사용 여부': dtype('int64'),
     '신선 배아 사용 여부': dtype('int64'),
     '기증 배아 사용 여부': dtype('int64'),
     '대리모 여부': dtype('int64'),
     'PGD 시술 여부': dtype('int64'),
     'PGS 시술 여부': dtype('int64'),
     '난자 출처': dtype('int64'),
     '정자 출처': dtype('int64'),
     '시술 당시 나이': dtype('int64'),
     '임신 시도 또는 마지막 임신 경과 연수': dtype('int64'),
     '총 시술 횟수': dtype('int64'),
     '클리닉 내 총 시술 횟수': dtype('int64'),
     'IVF 시술 횟수': dtype('int64'),
     'DI 시술 횟수': dtype('int64'),
     '총 임신 횟수': dtype('int64'),
     'IVF 임신 횟수': dtype('int64'),
     'DI 임신 횟수': dtype('int64'),
     '총 출산 횟수': dtype('int64'),
     'IVF 출산 횟수': dtype('int64'),
     'DI 출산 횟수': dtype('int64'),
     '총 생성 배아 수': dtype('int64'),
     '미세주입된 난자 수': dtype('int64'),
     '미세주입에서 생성된 배아 수': dtype('int64'),
     '이식된 배아 수': dtype('int64'),
     '미세주입 배아 이식 수': dtype('int64'),
     '저장된 배아 수': dtype('int64'),
     '미세주입 후 저장된 배아 수': dtype('int64'),
     '해동된 배아 수': dtype('int64'),
     '해동 난자 수': dtype('int64'),
     '수집된 신선 난자 수': dtype('int64'),
     '저장된 신선 난자 수': dtype('int64'),
     '혼합된 난자 수': dtype('int64'),
     '파트너 정자와 혼합된 난자 수': dtype('int64'),
     '기증자 정자와 혼합된 난자 수': dtype('int64'),
     '난자 기증자 나이': dtype('int64'),
     '정자 기증자 나이': dtype('int64'),
     '난자 혼합 경과일': dtype('int64'),
     '배아 이식 경과일': dtype('int64'),
     '배아 해동 경과일': dtype('int64'),
     'PGS': dtype('int64'),
     'PGD': dtype('int64'),
     '특시유_ICSI': dtype('int64'),
     '특시유_Unknown': dtype('int64'),
     '특시유_IVF': dtype('int64'),
     '특시유_ICSI/AH': dtype('int64'),
     '특시유_IVF/AH': dtype('int64'),
     '배생이_기증용': dtype('int64'),
     '임신 경험 여부': dtype('int64'),
     '출산 경험 여부': dtype('int64'),
     '시술 경험 여부': dtype('int64'),
     '단일_배아_이식_여부_수정': dtype('int64'),
     '클리닉 외 시술 여부': dtype('bool'),
     '배아 출처': dtype('int64'),
     '특정 시술 유형 (합산 유형)': dtype('int64'),
     '유전검사 (합산통합)': dtype('int64'),
     '불임원인 (합산통합)': dtype('int64'),
     '남성 불임 요인': dtype('int64'),
     '여성 불임 요인': dtype('int64'),
     'IVF_ICSI_최상조건': dtype('int64'),
     'IVF에서 생성된 배아 수': dtype('int64'),
     'IVF 배아 이식 수': dtype('int64'),
     'IVF 후 저장된 배아 수': dtype('int64'),
     '폐기된 배아 수': dtype('int64'),
     '미세주입 배아 실패 수': dtype('int64'),
     'IVF 배아 실패 수': dtype('int64'),
     '해당 주기 난자 주인 나이': dtype('int64'),
     '나이_X_이식수': dtype('int64'),
     '배란자극_X_이식배아수': dtype('int64'),
     '잉여_배아_수': dtype('int64'),
     '이식률': dtype('float64'),
     '수정률': dtype('float64'),
     '총 경과일 합계': dtype('int64'),
     '총 임신 실패 횟수': dtype('int64'),
     'IVF 임신 실패 횟수': dtype('int64'),
     'DI 임신 실패 횟수': dtype('int64'),
     '총 유산 횟수': dtype('int64'),
     'IVF 유산 횟수': dtype('int64'),
     'DI 유산 횟수': dtype('int64'),
     '기증자 나이 합산': dtype('int64'),
     '미세 주입 성공률': dtype('float64'),
     '난자 채취 이후 경과일': dtype('int64')}

   for c in df_AH.columns:
        df_AH[c] = df_AH[c].astype(d_types[c], errors='ignore')

   return df_AH